Place.create!([
  {name: "Benagil Sea Cave", description: "The Benagil Sea Cave is part of a system of caves that lines Portugal’s southern coast in the Algarve region. This most iconic cave is located just around the corner from a beach in the tiny town of Benagil. The coastline runs for about 150 kilometres and is dotted with alternating beaches, cliffs and caves, the latter of which bear interesting formations like skylights and often host picturesque variations of light throughout the day.", latitude: 37.0874, longitude: 8.4259, city: "Lagoa", state_province: nil, country: "Portugal", airport: "FAO", main_img:"http://i4.piimg.com/9510/209dcf9fa3878fd0.jpg"},
  {name: "Byodo-In Temple", description: "So peaceful and park-like, it might take you a minute to realize Valley of the Temples is an interdenominational cemetery. Up at the base of the Koʻolau mountain’s verdant fluted cliffs sits Byōdō-In, a replica of a 900-year-old temple in Uji, Japan. The symmetry is a classic example of Japanese Heian architecture, with rich vermillion walls. The 3-ton brass bell is said to bring peace and good fortune to anyone who rings it.", latitude: 21.4307, longitude: 157.8322, city: "Ahiumanu", state_province: nil, country: "Hawaii", airport: "HNL", main_img:"http://damedovolenou.com/wp-content/uploads/2016/06/Japonsko.jpg"},
  {name: "Machu Picchu", description: "Dating to the mid-1400s, Machu Picchu is a marvel of mortar-free limestone architecture perched on a high plateau deep in the Amazonian jungle. In a spectacular location, it’s the best-known archaeological site on the continent. This awe-inspiring ancient city was never revealed to the conquering Spaniards and was virtually forgotten until the early part of the 20th century.", latitude: 13.1631, longitude: 72.545, city: "Cuzco", state_province: nil, country: "Peru", airport: "CUZ", main_img:"http://travelier.mx/wp-content/uploads/2015/12/Fotolia_69910180_Subscription_Monthly_M.jpg"},
  {name: "Mù Cang Chải", description: "Every year, between September and October, the terraced rice fields of Mù Cang Chải, a rural district in northern Vietnam’s Yên Bái Province, put on a show of picturesque harvest colours. In the fresh, dew-brushed dawn, hundreds of stepped rice fields, carved into the contours of steep valleys, are illuminated by the autumn sun.", latitude: 21.767, longitude: 104.1466, city: "YenBai", state_province: "Yen Bai", country: "Vietnam", airport: "SQH", main_img:"http://travelier.mx/wp-content/uploads/2015/12/Fotolia_69910180_Subscription_Monthly_M.jpg"},
  {name: "Travertine Hot Springs", description: "The surreal, brilliant white travertine terraces and warm, limpid pools of Pamukkale hang from the rim of a steep valley side in Turkey’s picturesque southwest. Truly spectacular in its own right, the geological phenomenon that is Pamukkale is also the site of the remarkably well-preserved ruins of the Greek-Roman city of Hierapolis. With such a unique combination of natural and man-made wonders it’s little wonder that Pamukkale-Hierapolis has been made a Unesco World Heritage site.", latitude: 37.9186, longitude: 29.1103, city: "Denizli", state_province: "Denizli Province", country: "Turkey", airport: "DNZ", main_img:"http://thoidai.com.vn/data/data/nguyenvu/files/gam-mau-ruc-ro-tren-nhung-thua-ruong-bac-thang/4.jpg"},
  {name: "Procida", description: "The Bay of Naples’ smallest island is also its best-kept secret. Dig out your paintbox: this soulful blend of lemon groves and pastel-hued houses is memorably picturesque. Mercifully off the mass-tourist radar, Procida is like the Portofino prototype and is refreshingly real. August aside – when beach-bound mainlanders flock to its shores – its narrow, sun-bleached streets are the domain of the locals: young boys clutch fishing rods, mothers push prams and old seamen swap yarns.", latitude: 40.7578, longitude: 14.0151, city: "Procida Island", state_province: nil, country: "Italy", airport: "NAP", main_img:"http://www.brotherstaxikusadasi.com/wp-content/uploads/photo-gallery/pamukkale%20(28).jpg"},
  {name: "Ahu Tongariki", description: "The monumental Ahu Tongariki has plenty to set your camera's flash popping. With 15 imposing statues, it is the largest ahu ever built. The statues gaze over a large, level village site, with ruined remnants scattered about and some petroglyphs nearby; some figures include a turtle with a human face, a tuna fish and a birdman motif.", latitude: 27.113, longitude: 109.3496, city: "Easter Island", state_province: nil, country: "Chile", airport: "IPC", main_img:"http://api.ning.com/files/t7OHPZDdmLu8TgQu1Nr00X1*eCWQt1j2-rxg06eNBPb0gD-5Km8HyhocR9UnpD-V5rpyaJSJ*Wh2ok6Bz2278rYXw8QCvBKm/RapaNui011.jpg"},
  {name: "Mohatta Palace", description: "Near the Ziarat of Abdullah Shah Gazi is the Mohatta Palace, another residence of Jinnah's sister Fatima, a fine British Raj building that has enjoyed a new lease of life following its restoration in 1999. The exhibtions detail the history of Pakistan's distinctive artistic heritage while the gardens offer some fine relief from Karachi's crowded mayhem.", latitude: 24.8146, longitude: 67.0325, city: "Karachi", state_province: nil, country: "Pakistan", airport: "KHI", main_img:"https://upload.wikimedia.org/wikipedia/commons/e/eb/Mohatta_Palace.jpg"},
  {name: "Turkey Hot Air Balloons", description: "Down in the valley...a hot-air balloon drifts right among the chimneys of Cappadocia. As if plucked from a whimsical fairytale and set down upon the stark Anatolian plains, Cappadocia is a geological oddity of honeycombed hills and towering boulders of otherworldly beauty. Whether you're wooed here by the hiking potential, the history or the bragging rights of becoming a modern troglodyte for a night, it's the lunarscape panoramas that you'll remember. This region's accordion-ridged valleys, shaded in a palette of dusky orange and cream, are an epiphany of a landscape – the stuff of psychedelic daydreams.", latitude: 38.6463, longitude: 34.8423, city: "Cappadocia", state_province: nil, country: "Turkey", airport: "NAV", main_img:"http://atis.com.sg/deal/static/team/2015/0910/14418756001329.jpg", video: "https://vimeo.com/26135773", main_img2: "http://www.whynottravelnow.com/wp-content/uploads/2016/05/Hot-air-balloon-over-Cappadocia.jpg", main_img3: "http://theredlist.com/media/database/architecture/history/architecture-byzantine/sanctuaire-rupestres-cappadoce%20/005_sanctuaire-rupestres-cappadoce_theredlist.jpg"}
])
User.create!([
  {name: "Jessica", email: "jcotzin@gmail.com", password_digest: "$2a$10$LZ.Xc4TOBHkjx7z6trZdYOUPMsG6Ddxhr54337irFHZexPbiNQ6JG"}
])
Tag.create!([
  {name:"Adventure"},
  {name:"Beaches"},
  {name:"Budget"},
  {name:"Family"},
  {name:"Honeymoon"},
  {name:"Romance"},
  {name:"Tropical"},
  {name:"Luxury"},
  {name:"Wildlife"},
  {name:"Outdoor"},
  {name:"Nature"},
  {name:"Historic"},
  ])
# places.each do |place|
#   Place.create!(place)
# end
